### ISSUE TITLE
expired reference not removed during call to Observerable.inform()

### ISSUE THREAD

**Issue by derikd** [creichlin/struwwel#1]
On line 39 of the August 10 commit of Observable I see the following.
    tor.removeAll(tor);

I was expecting
    observers.removeAll(tor);

As I understand it, the variable 'tor' contains a list of all the weak references toRemove from the observers list.   That is, a list of all WeakRefererences from 'observers' whose whose get() method returned null.  

I also have a second question.   When I call Observerable.register() it returns an ObservableReference so that I can chain a call to keepFor(someObject).    If I don't keep a reference to that ObservableReference, then it, and the WeakHashMap that it contains, could be GC'ed at any point thereafter; they won't act as a guard against the observer getting GC'ed before someObject is GC'd.  

It seems like the forInstance field of ObservableReference needs to be in the Observable class.   That is still not protection against the observer getting GC'ed before someObject, but if the Observable has been GC'd and no one else has a reference to Observer, then it is always safe to GC Observer regardless of the state of someObject.

**Comment by creichlin** [comment]
When the Observable.register(...) is called it will register the listener and add it to a hard reference and will be kept therefore. Only when reference.keepFor(...) is called it will be removed from that hard reference.

**Comment by derikd** [comment]
thanks for the quick reply.

I agree that when you call ObserverReference.keepFor() the obsererver added to the WeakHashMap, forInstance, and is subsequently removed from the hard list.  After that call, the only thing protecting that observer from being GC'ed is the reference to observer in WeakHashMap.   Do I have that right?    So who is responsible for protecting the WeakHashMap?   Well obviously it is referred to by the instance of ObserverReference which is returned by the call to Observable.register().    But in your usage example, that object falls out of scope almost as soon as it is created.

```
 Observable observable = new Observable();
 Object token = new Object();
 observable.register(new Observer()).keepFor(token);
```

You logically chain the keepFor() command directly return value of register, but you don't save the return value of that function.  So the next time the GC runs it will clean up the object returned by register(), the WeakHashMap that is contained by that object, and ultimately the observer, which is now not referenced by anything (except the weak reference in Oberverable.observers).

At least that is how it looks to me.  Maybe I am missing something important.

**Comment by creichlin** [comment]
The WeakHashMap _forInstance_ is static so it will survive the garbage collection of the instances.

**Comment by derikd** [comment]
Oops. I completely missed that.  Thanks for explaining it to me.

On Sep 29, 2015, at 1:13 PM, Chrigi <notifications@github.com<mailto:notifications@github.com>> wrote:

The WeakHashMap forInstance is static so it will survive the garbage collection of the instances.

**Comment by creichlin** [comment]
I cleaned the code a bit, might be a bit easier to read now. That you missed the static was kind of my fault. I added the static variable after the instance variables which is misleading and bad practice.
